apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: lifewatch
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lifewatch
  template:
    metadata:
      labels:
        app: lifewatch
    spec:
      containers:
      - name: lifewatch
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
