apiVersion: v1
kind: Service
metadata:
  name: lifewatch-service
spec:
  selector:
    app: lifewatch
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
