apiVersion: v1
kind: Namespace
metadata:
  name: argo

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo
  namespace: argo
spec:
  chart:
    spec:
      chart: argo-workflows
      version: 0.45.10
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argo
  interval: 5m
  values:
    server:
      authMode: server
    service:
      type: LoadBalancer