apiVersion: apps/v1 
kind: Deployment
metadata:
  name: lifewatch-deployment
  labels: 
     app: lifewatch-app

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: lifewatch-app

  template:
    metadata:
      labels:
        app: lifewatch-app
    spec:
      containers:
      - name: lifewatch-app
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1