apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifewatch-deployment
  labels:
    app: lifewatch-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifewatch-app
  template:
    metadata:
      labels:
        app: lifewatch-app
    spec:
      containers:
      - name: lifewatch-app
        image: 940482412682.dkr.ecr.eu-central-1.amazonaws.com/lifewatch:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: UVA_MINIO_API
          value: ${UVA_MINIO_API}
        - name: SPAIN_MINIO_API
          value: ${SPAIN_MINIO_API}
        - name: MINIO_REGION
          value: ${MINIO_REGION}
        - name: MINIO_ACCESS_KEY_ID
          value: ${MINIO_ACCESS_KEY_ID}
        - name: MINIO_ACCESS_KEY
          value: ${MINIO_ACCESS_KEY}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1