version: '3.8'

services:
  lifewatch:
    image: lifewatch
    build: .
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      FLASK_ENV: development  # Enable Flask development mode
      UVA_MINIO_API: ${UVA_MINIO_API}
      SPAIN_MINIO_API: ${SPAIN_MINIO_API}
      MINIO_REGION: ${MINIO_REGION}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}

    volumes:
      - .:/usr/src/app
      - /usr/src/app/venv  # Prevents venv from being overwritten

    restart: always
