version: '3.8'

services:
  workflow-api:
    image: workflow-api
    build: .
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    restart: always
